---
# tasks file for ospf

- name: OSPF=>> Get configs from routers
  ios_command:
    commands: "sh run"
  register: res_sh_run

- name: OSPF=>> Prepare config OSPF for delete
  set_fact:
    int_info: "{{ res_sh_run.stdout[0] | ios_run_conf_int_ospf(True) }}"

- name: OSPF=>> Show config for delete
  debug:
    msg: 
      - "{{ int_info }}"



