---
# tasks file for ospf
- name: OSPF=>> Get config from routers
  ios_command:
    commands:
      - sh run
  register: res_sh_run
  tags:
    - cfg_show

- name: OSPF=>> Prepare config OSPF for show
  set_fact:
    int_info: "{{ res_sh_run.stdout[0] | ios_run_conf_int_ospf(False) }}"
  tags:
    - cfg_show

- name: OSPF=>> Show OSPF cfg
  debug: 
    msg: "{{ int_info }}"
  tags:
    - cfg_show
#  and length: {{ospf_cfg.stdout_lines | length }}
