---
# tasks file for ospf
- name: Write OSPF cfg in variable
  ios_command:
    commands:
      - sh run | s ^router ospf
  register: ospf_cfg
  when: inventory_hostname in ospfs  
  tags:
    - cfg_show

- name: Show OSPF cfg
  debug: 
    msg: "{{ ospf_cfg.stdout_lines[0] }}"
  when: inventory_hostname in ospfs and ospf_cfg.stdout_lines[0] | length > 1 
  tags:
    - cfg_show
#  and length: {{ospf_cfg.stdout_lines | length }}
