---
# tasks file for DMVPN
- name: "Delete old local DMVPN CRYPTO configuration files"
  file:
    path: "{{cfg_dmvpn_path}}/dmvpn_crypto_{{ inventory_hostname }}.txt"
    state: absent
  tags:
    - gen_cfg

- name: Set fact current DMVPN CRYPTO
  set_fact:
    current_crypto_profile: "{{ ansible_net_config | regex_findall('\\ncrypto ipsec profile(.*)') }}"
    current_crypto_transoform_set: "{{ ansible_net_config | regex_findall('\\ncrypto ipsec transform-set(.*)') }}"
    current_crypto_ike_profile: "{{ ansible_net_config | regex_findall('\\ncrypto ikev2 profile(.*)') }}"
    current_crypto_keyring: "{{ ansible_net_config | regex_findall('\\ncrypto ikev2 keyring(.*)') }}"
    current_crypto_ike_policy: "{{ ansible_net_config | regex_findall('\\ncrypto ikev2 policy(.*)') }}"
    current_crypto_ike_proposal: "{{ ansible_net_config | regex_findall('\\ncrypto ikev2 proposal(.*)') }}"
#  when: inventory_hostname in dmvpn_hosts  and do_it|bool
  tags:
    - cfg_del_crypto
    - cfg_del

# - name: Show var current_dmvpn_tuns
#   debug: 
#     msg:
#       - "{{ current_crypto_profile }}"
#       - "{{ current_crypto_transoform_set }}"
#       - "{{ current_crypto_ike_profile }}"
#       - "{{ current_crypto_keyring }}"
#       - "{{ current_crypto_ike_policy }}"
#       - "{{ current_crypto_ike_proposal }}"
#   when: inventory_hostname in dmvpn_hosts        
#   tags:
#     - cfg_del_crypto
#     - cfg_del

- name: "Delete  CRYPTO DMVPN on router from configuration file "
  ios_config:
    src: dmvpn_del_crypto.j2
    backup: no
#  when: inventory_hostname in dmvpn_hosts and do_it|bool
  tags:
    - cfg_del_crypto
    - cfg_del

- name: "Generating new local CRYPTO DMVPN configuration files"
  template:
    src: dmvpn_crypto.j2
    dest: "{{cfg_dmvpn_path}}/dmvpn_crypto_{{ inventory_hostname }}.txt"
    trim_blocks: True
    lstrip_blocks: True
  when: inventory_hostname in dmvpn_hosts 
  tags:
    - gen_cfg

- name: "Configure DMVPN CRYPTO on router from configuration file "
  ios_config:
    src: "{{cfg_dmvpn_path}}/dmvpn_crypto_{{ inventory_hostname }}.txt"
    backup: no
  when: inventory_hostname in dmvpn_hosts  and do_it|bool

