---
# tasks file for EIGRP
- name: Write Route-Maps cfg in variable
  ios_command:
    commands:
      - sh run | s ^route-map
      - sh run | s ^access-list      
      - sh run | s ^ip access-list
      - sh run | s ^ip prefix-list
  register: rm_cfg
  tags:
    - cfg_show

- name: Show Route-Maps cfg
  debug: 
    msg: "{{ rm_cfg.stdout_lines }}"
  when: rm_cfg.stdout_lines is defined
  tags:
    - cfg_show

