---
### Configure interfaces
- name: HUAWEI INTERFACE=>> Configure Interfaces IPv4
  ansible.netcommon.cli_command:
    command: |
      system-view
      interface {{ item.name }}
       ip address {{ item.ipv4|ipaddr('address') }} {{ item.ipv4|ipaddr('netmask') }}
       undo shutdown
       return
  #when: 'ipv4' in item
  loop: "{{ interfaces }}"
  when: interfaces is defined and 'ipv4' in item

- name: HUAWEI INTERFACE=>> Configure Interfaces IPv6
  ansible.netcommon.cli_command:
    command: |
      system-view
      ipv6
      interface {{ item.name }}
       ipv6 enable
       ipv6 address {{ item.ipv6 }}
       undo shutdown
       return
  
  loop: "{{ interfaces }}"
  when: interfaces is defined and 'ipv6' in item

- name: HUAWEI INTERFACE=>> Get information about Interfaces ipv4
  ansible.netcommon.cli_command:
    command: dis ip interface br
  register: result

- name: HUAWEI INTERFACE=>> Show information
  debug:
    msg: "{{ result.stdout }}"


- name: HUAWEI INTERFACE=>> Get information about Interfaces ipv6
  ansible.netcommon.cli_command:
    command: dis ipv6 interface br
  register: result

- name: HUAWEI INTERFACE=>> Show information
  debug:
    msg: "{{ result.stdout }}"


