---
# tasks file for interfaces
- name: "Reset Interfaces"
  ios_config:
    lines: "default interface {{ item.name }}"
  when: item.name is not search("loopback") 
  loop: "{{ interfaces }}"
  # and interfaces is defined
  
