---
# tasks file for interfaces
- name: "Reset Interfaces"
  import_tasks: int_reset.yml
  when: int_reset !=  False
  tags:
    - int_reset

- name: "Configure interfaces"
  ios_config:
    src: int_eveng.j2
    backup: no
  register: result_int

- name: "Configure hostname"
  ios_config: 
    lines: 
      - "hostname {{ inventory_hostname }}"

- name: "UP interfaces"
  ios_interface:
    name: "{{ item['int'] }}"
    enabled: True
  loop: "{{ interfaces[inventory_hostname] }}"
  register: result_up

- name: "Save Configuration "
  ios_command: 
    commands: wr mem
  when: result_int.changed or result_up.changed
