---
# tasks file for interfaces
# - name: View bool variables
#   debug: 
#     msg: 
#       - "{{ do_it }}"
#       - "{{ int_reset }}"

- name: "Configure Interfaces"
  include_tasks: "{{ net_os }}_interfaces.yml"
  when: 
    - int_reset|bool 
    - do_it|bool 
    - interfaces is defined
