---
# tasks file for interfaces
- debug: var={{ do_it }}

- name: "Reset Interfaces"
  import_tasks: int_reset.yml
  when: int_reset !=  False and do_it == True
  tags:
    - int_reset

- name: "Configure interfaces"
  ios_config:
    src: int_eveng.j2
    backup: no
  register: result_int
  when: do_it == True

- name: "Configure hostname"
  ios_config: 
    lines: 
      - "hostname {{ inventory_hostname }}"
  when: do_it == True

- name: "UP interfaces"
  ios_interface:
    name: "{{ item['int'] }}"
    enabled: True
  loop: "{{ interfaces[inventory_hostname] }}"
  register: result_up
  when: do_it == True

- name: "Save Configuration "
  ios_command: 
    commands: wr mem
  when: result_int.changed or result_up.changed and do_it == True

