---
# tasks file for EIGRP

- name: EIGRP=>> Collect facts
  ios_facts:
    gather_subset:
      - "!hardware"

- name: EIGRP=>> Set fact current EIGRP 
  set_fact:
    current_eigrp: "{{ ansible_net_config | regex_findall('router eigrp (.*)') }}"

- name: EIGRP=>> Show var current_eigrp for delete
  debug: 
    msg: "{{ current_eigrp }}"
