---
# tasks file for EIGRP
- name: EIGRP=>> Write EIGRP cfg in variable
  ios_command:
    commands:
      - sh run | s ^router eigrp
  register: eigrp_cfg

- name: EIGRP=>> Show EIGRP cfg
  debug: 
    msg: "{{ eigrp_cfg.stdout_lines[0] }}"
  when: eigrp_cfg.stdout_lines[0] | length > 1


