---
# tasks file for EIGRP
- name: "EIGRP=>> Get and Delete old EIGRP configuration "
  import_tasks: eigrp_del.yml
#  when: do_it|bool
  tags:
    - eigrp_del
    - all_del
    - eigrp_cfg

- name: "EIGRP=>> Delete old cfg EIGRP on router"
  ios_config:
    lines: "no router eigrp {{ item }}"
    backup: no
  when: current_eigrp is defined and current_eigrp | length > 0
  loop: "{{ current_eigrp }}"
  tags:
    - eigrp_del
    - eigrp_cfg
    - all_del

- name: "EIGRP=>> Check directory for config files "
  file:
    path: "{{cfg_eigrp_path}}"
    state: directory
  changed_when: false
  run_once: true
  tags:
    - eigrp_cfg
    - eigrp_gen

- name: "EIGRP=>> Delete old local EIGRP cfg files from dir: {{ cfg_eigrp_path }} "
  file:
    path: "{{cfg_eigrp_path}}/eigrp_{{ inventory_hostname }}.txt"
    state: absent
  tags:
    - eigrp_cfg
    - eigrp_gen

- name: "EIGRP=>> Generating new local EIGRP cfg files in dir: {{ cfg_eigrp_path }}"
  template:
    src: eigrp_eveng.j2
    dest: "{{cfg_eigrp_path}}/eigrp_{{ inventory_hostname }}.txt"
    trim_blocks: True
    lstrip_blocks: True
  when: eigrp is defined and eigrp | length > 0
  tags:
    - eigrp_cfg
    - eigrp_gen

- name: "EIGRP=>> Configure EIGRP on router from created cfg file "
  ios_config:
    src: "{{cfg_eigrp_path}}/eigrp_{{ inventory_hostname }}.txt"
    backup: no
  when: eigrp is defined and eigrp | length > 0    
  tags:
    - eigrp_cfg

- name: "EIGRP=>> Show current EIGRP configuration "
  import_tasks: eigrp_show.yml
  tags:
    - eigrp_cfg
    - eigrp_view


