---
# tasks file for ansible

- name: "ANSIBLE=>> Select Distributive"
  include_tasks: "{{ net_os }}_ansible.yml"
  when: 
    - ansible_role is defined
    - ansible_role|bool 
    - net_os is defined
