---
# tasks file for jenkins

- name: "JENKINS=>> Select Distributive"
  include_tasks: "{{ net_os }}_jenkins.yml"
  when: 
    - jenkins_role is defined
    - jenkins_role|bool 
    - net_os is defined
